# Generated by Django 4.0 on 2024-04-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0003_product_cartitem_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(editable=False, max_length=150, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
