# Generated by Django 4.0 on 2024-04-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0004_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
