# Generated by Django 4.0 on 2024-04-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0005_alter_customerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
