# Generated by Django 4.0 on 2024-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0007_alter_customerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
