# Generated by Django 4.0 on 2024-04-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0008_alter_customerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earring_app.customerprofile'),
        ),
    ]
