# Generated by Django 4.0 on 2024-04-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0009_alter_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
