# Generated by Django 4.0 on 2024-04-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0012_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date_added',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='orderid',
            field=models.CharField(default='not set', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.CharField(default='not set', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.CharField(max_length=200),
        ),
    ]
