# Generated by Django 4.0 on 2024-04-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0013_remove_orders_date_added_cartitem_orderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.CharField(default='not set', max_length=200),
        ),
    ]
