# Generated by Django 4.0 on 2024-04-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0014_orders_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='not set', max_length=250),
        ),
        migrations.AddField(
            model_name='orders',
            name='contact',
            field=models.CharField(default='not set', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='fname',
            field=models.CharField(default='not set', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='lname',
            field=models.CharField(default='not set', max_length=100),
        ),
    ]
