# Generated by Django 4.0 on 2024-04-14 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0015_orders_address_orders_contact_orders_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earring_app.category'),
        ),
    ]
