# Generated by Django 4.0 on 2024-04-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
