# Generated by Django 4.0 on 2024-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earring_app', '0017_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sstatus',
            field=models.CharField(default='not set', max_length=20),
        ),
    ]
